### ISSUE TITLE
Down?

### ISSUE THREAD

**Issue by aaronmgdr** [AlexBHarley/plock.fi#3]
looks like its down> 

is that official?

@AlexBHarley

**Comment by AlexBHarley** [comment]
@aaronmgdr the domain name expired and I didn't bother to renew

**Comment by AlexBHarley** [comment]
Via Vercel though it's available at [celo-dapp.vercel.app](https://celo-dapp.vercel.app/) and [plock-fi-alexbharley.vercel.app](https://plock-fi-alexbharley.vercel.app/)
